name: pide ayuda
description: pide ayuda
labels: [ "help wanted" ]
assignees:
  - balugaq
body:
  - type: markdown
    attributes:
      value: |
        ## bienvenido a JustEnoughGuide rastreador de problemas
        Estás solicitando ayuda para resolver JustEnoughGuide pregunta。

        <strong><i>Debes rellenar los campos marcados con un asterisco（*）elemento de formulario</i></strong>

  - type: checkboxes
    id: checklist
    attributes:
      label: comprobar artículos
      description: Antes de informar, debe confirmar
      options:
        - label: ya has buscado[Lista de problemas conocidos](https://github.com/balugaq/JustEnoughGuide/issues)，y no se encontraron problemas similares
          required: true

  - type: textarea
    id: description
    attributes:
      label: Descripción del problema
      description: |
        Describe detalladamente el problema que deseas reportar.
        Proporcionar información detallada nos permite resolver problemas más rápido
      placeholder: solo di"El ____ no funciona"Los desarrolladores no tienen forma de localizar el problema.。
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft Versión
      description: Por favor complete su Minecraft Versión
    validations:
      required: true

  - type: textarea
    id: slimefun-version
    attributes:
      label: SlimefunVersión
      description: |
        Por favor completeSlimefunVersión
        (Por ejemplo v4.9-canary-08120db)
        Si tiene derechos de administrador, se recomienda ejecutar`/sf versions`comando, captura de pantalla y cargue el resultado del comando aquí**Todo el contenido**。
    validations:
      required: true

  - type: input
    id: version-plugin
    attributes:
      label: Versión del complemento
      description: |
        Por favor complete la versión del complemento
