name: Otras preguntas
description: Otras preguntas
labels: [ "need tag" ]
assignees:
  - balugaq
body:
  - type: markdown
    attributes:
      value: |
        ## bienvenido a JustEnoughGuide rastreador de problemas
        
        <strong><i>Debes rellenar los campos marcados con un asterisco（*）elemento de formulario</i></strong>

  - type: checkboxes
    id: checklist
    attributes:
      label: comprobar artículos
      description: Antes de informar, debe confirmar
      options:
        - label: ya has buscado[Lista de problemas conocidos](https://github.com/balugaq/JustEnoughGuide/issues)，y no se encontraron sugerencias similares
          required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Descripción del problema
      description: |
        Describe tu problema detalladamente
    validations:
      required: true
