name: Sugerencias y comentarios de desarrollo.
description: Hacer sugerencias de desarrollo.
labels: [ "suggestion" ]
assignees:
  - balugaq
body:
  - type: markdown
    attributes:
      value: |
        ## bienvenido a JustEnoughGuide rastreador de problemas
        estas proponiendo JustEnoughGuide sugerencias de desarrollo。
        
        <strong><i>Debes rellenar los campos marcados con un asterisco（*）elemento de formulario</i></strong>

  - type: checkboxes
    id: checklist
    attributes:
      label: comprobar artículos
      description: Antes de informar, debe confirmar
      options:
        - label: ya has buscado[Lista de problemas conocidos](https://github.com/balugaq/JustEnoughGuide/issues)，y no se encontraron sugerencias similares
          required: true

  - type: textarea
    id: reason
    attributes:
      label: Motivación de la propuesta
      description: |
        Describe detalladamente por qué haces esta sugerencia.
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Contenido propuesto
      description: |
        Describe en detalle las características que deseas implementar o sugerencias de mejora.
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: información adicional
      description: |
        En caso afirmativo, proporcione más información.。
